[2024-02-05T19:49:54.868+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crypto_ETL.coinmarketcap_fetch_data manual__2024-02-05T19:49:52.838711+00:00 [queued]>
[2024-02-05T19:49:54.888+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crypto_ETL.coinmarketcap_fetch_data manual__2024-02-05T19:49:52.838711+00:00 [queued]>
[2024-02-05T19:49:54.889+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-05T19:49:54.916+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): coinmarketcap_fetch_data> on 2024-02-05 19:49:52.838711+00:00
[2024-02-05T19:49:54.924+0000] {standard_task_runner.py:60} INFO - Started process 4816 to run task
[2024-02-05T19:49:54.930+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_crypto_ETL', 'coinmarketcap_fetch_data', 'manual__2024-02-05T19:49:52.838711+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dag_v1.py', '--cfg-path', '/tmp/tmpj6cjvq3_']
[2024-02-05T19:49:54.936+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask coinmarketcap_fetch_data
[2024-02-05T19:49:55.033+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_crypto_ETL.coinmarketcap_fetch_data manual__2024-02-05T19:49:52.838711+00:00 [running]> on host 0fd5da028511
[2024-02-05T19:49:55.386+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crypto_ETL' AIRFLOW_CTX_TASK_ID='coinmarketcap_fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T19:49:52.838711+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-05T19:49:52.838711+00:00'
[2024-02-05T19:49:55.931+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coinmarketcap_fetch_data.py", line 28, in fetch_data
    file.write(json_data)
TypeError: write() argument must be str, not dict
[2024-02-05T19:49:55.953+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_crypto_ETL, task_id=coinmarketcap_fetch_data, execution_date=20240205T194952, start_date=20240205T194954, end_date=20240205T194955
[2024-02-05T19:49:55.983+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task coinmarketcap_fetch_data (write() argument must be str, not dict; 4816)
[2024-02-05T19:49:56.033+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-05T19:49:56.061+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
