[2024-02-05T16:07:11.388+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crypto_ETL.transform_to_pandas manual__2024-02-05T16:07:07.727377+00:00 [queued]>
[2024-02-05T16:07:11.401+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crypto_ETL.transform_to_pandas manual__2024-02-05T16:07:07.727377+00:00 [queued]>
[2024-02-05T16:07:11.402+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-05T16:07:11.419+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_to_pandas> on 2024-02-05 16:07:07.727377+00:00
[2024-02-05T16:07:11.426+0000] {standard_task_runner.py:60} INFO - Started process 1405 to run task
[2024-02-05T16:07:11.430+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_crypto_ETL', 'transform_to_pandas', 'manual__2024-02-05T16:07:07.727377+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_v1.py', '--cfg-path', '/tmp/tmpuvp_vahd']
[2024-02-05T16:07:11.434+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask transform_to_pandas
[2024-02-05T16:07:11.503+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_crypto_ETL.transform_to_pandas manual__2024-02-05T16:07:07.727377+00:00 [running]> on host 0fd5da028511
[2024-02-05T16:07:11.769+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crypto_ETL' AIRFLOW_CTX_TASK_ID='transform_to_pandas' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T16:07:07.727377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-05T16:07:07.727377+00:00'
[2024-02-05T16:07:11.771+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: transform() missing 1 required positional argument: 'data'
[2024-02-05T16:07:11.780+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_crypto_ETL, task_id=transform_to_pandas, execution_date=20240205T160707, start_date=20240205T160711, end_date=20240205T160711
[2024-02-05T16:07:11.794+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task transform_to_pandas (transform() missing 1 required positional argument: 'data'; 1405)
[2024-02-05T16:07:11.806+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-05T16:07:11.824+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
